name: MixMod workflow

on:
  workflow_dispatch:
    inputs:
      override_version:
        description: 'Override release tag version'
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Get next version
        if: ${{ !github.event.inputs.override_version }}
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: libimage-exiftool-perl
          version: 1.0

      - name: Make Downloads dir
        run: |
          mkdir -p ../Downloads
          echo "Downloads_Dir=$(realpath ../Downloads/)" >> $GITHUB_ENV

      - name: Get CASCConsole latest release info
        run: |
          curl --silent https://api.github.com/repos/DeNcHiK3713/CASCExplorer/releases >> ${{ runner.temp }}/CASCConsole_release_info.json
          echo "CASCConsole_asset_id=$(jq -r 'map(select(.prerelease)) | first | .assets[] | select(.name | contains("linux-x64")) | .id' ${{ runner.temp }}/CASCConsole_release_info.json)" >> $GITHUB_ENV

      - name: Cache CASCConsole
        id: CASCConsole-cache
        uses: actions/cache@v5
        with:
          path: ${{ env.Downloads_Dir }}/CASCConsole
          key: CASCConsole-${{ runner.os }}-${{ env.CASCConsole_asset_id }}

      - name: Download CASCConsole
        if: steps.CASCConsole-cache.outputs.cache-hit != 'true'
        working-directory: ${{ env.Downloads_Dir }}
        run: |
          wget $(jq -r 'map(select(.prerelease)) | first | .assets[] | select(.name | contains("linux-x64")) | .browser_download_url' ${{ runner.temp }}/CASCConsole_release_info.json) -O CASCConsole.zip
          unzip CASCConsole.zip -d CASCConsole
          chmod +x ./CASCConsole/CASCConsole

      - name: Download files
        working-directory: ${{ env.Downloads_Dir }}
        run: |
          ./CASCConsole/CASCConsole -m Pattern -e Hearthstone_Data/Managed/Assembly-CSharp.dll -o -p hsb -l None -d ./
          ./CASCConsole/CASCConsole -m Pattern -e Hearthstone_Data/Managed/Assembly-CSharp-firstpass.dll -o -p hsb -l None -d ./
          ./CASCConsole/CASCConsole -m Pattern -e Hearthstone_Data/Managed/blizzard.bgsclient.dll -o -p hsb -l None -d ./
          ./CASCConsole/CASCConsole -m Pattern -e Hearthstone_Data/Managed/Blizzard.T5.Configuration.dll -o -p hsb -l None -d ./
          ./CASCConsole/CASCConsole -m Pattern -e Hearthstone_Data/Managed/Blizzard.T5.Core.dll -o -p hsb -l None -d ./
          ./CASCConsole/CASCConsole -m Pattern -e Hearthstone_Data/Managed/Blizzard.T5.Localization.dll -o -p hsb -l None -d ./
          ./CASCConsole/CASCConsole -m Pattern -e Hearthstone.exe -o -p hsb -l None -d ./
          UnityVersion=$(exiftool -ProductVersion -b Hearthstone.exe)
          echo "unity_version=${UnityVersion%%f*}" >> $GITHUB_ENV

      - name: Edit csproj file
        run: |
          sed -i "s/<Version>.*<\/Version>/<Version>${{ github.event.inputs.override_version || steps.version.outputs.version }}<\/Version>/" ./MixMod/MixMod.csproj
          sed -i "s/<PackageReference Include=\"UnityEngine.Modules\" Version=\".*\" IncludeAssets=\"compile\" \/>/<PackageReference Include=\"UnityEngine.Modules\" Version=\"${{ env.unity_version }}\" IncludeAssets=\"compile\" \/>/" ./MixMod/MixMod.csproj

      - name: Commit changes
        id: git_auto_commit
        uses: stefanzweifel/git-auto-commit-action@v7

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Make Release dir
        run: mkdir -p ${{ runner.temp }}/Release

      - name: Make packages
        working-directory: ${{ runner.temp }}/Release
        run: |
          mkdir -p plugins
          cp -r ${{ github.workspace }}/MixMod/bin/Release/net481/MixMod.dll $(ls -d ${{ github.workspace }}/MixMod/bin/Release/net481/*/) ./plugins/
          zip -9 -r MixMod_${{ github.event.inputs.override_version || steps.version.outputs.version }}.zip ./plugins/MixMod.dll $(ls -d ./plugins/*/)

      - uses: "ncipollo/release-action@v1"
        with:
          tag: "v${{ github.event.inputs.override_version || steps.version.outputs.version }}"
          name: "MixMod"
          artifacts: "${{ runner.temp }}/Release/MixMod_*.zip"
